services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth:/app
    ports:
      - 8000:8000
  file_manager:
    build:
      context: ./services/file_manager
      dockerfile: Dockerfile
    volumes:
      - ./services/file_manager:/app
    working_dir: /app
    ports:
      - 8001:8001
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./services/db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # delete this line if you don't want to expose the port
  queue:
    image: rabbitmq:3.13-management
    restart: always
    volumes:
      - ./services/rabbitmq/data:/var/lib/rabbitmq
